name: Update cache bust parameter on README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update cache_bust parameter in README.md
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        echo "Timestamp: $TIMESTAMP"
        sed -i "s/cache_bust=[0-9]\+/cache_bust=$TIMESTAMP/g" README.md

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "chore: update cache_bust parameter to $TIMESTAMP" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
